// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getEdgeNetworkCalc
IntegerMatrix getEdgeNetworkCalc(IntegerMatrix inputEdgeList);
RcppExport SEXP pii_getEdgeNetworkCalc(SEXP inputEdgeListSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type inputEdgeList(inputEdgeListSEXP);
    __result = Rcpp::wrap(getEdgeNetworkCalc(inputEdgeList));
    return __result;
END_RCPP
}
// piiCalc
NumericVector piiCalc(IntegerMatrix edgeDistance, NumericVector valence, double piiBeta, double piiX, int maxDistance);
RcppExport SEXP pii_piiCalc(SEXP edgeDistanceSEXP, SEXP valenceSEXP, SEXP piiBetaSEXP, SEXP piiXSEXP, SEXP maxDistanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edgeDistance(edgeDistanceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type valence(valenceSEXP);
    Rcpp::traits::input_parameter< double >::type piiBeta(piiBetaSEXP);
    Rcpp::traits::input_parameter< double >::type piiX(piiXSEXP);
    Rcpp::traits::input_parameter< int >::type maxDistance(maxDistanceSEXP);
    __result = Rcpp::wrap(piiCalc(edgeDistance, valence, piiBeta, piiX, maxDistance));
    return __result;
END_RCPP
}
// piiTriadicCalc
NumericVector piiTriadicCalc(IntegerMatrix edgeDistance, NumericVector valence, double piiBeta, double piiX, int maxDistance, LogicalVector edgeTriadic, double piiDelta);
RcppExport SEXP pii_piiTriadicCalc(SEXP edgeDistanceSEXP, SEXP valenceSEXP, SEXP piiBetaSEXP, SEXP piiXSEXP, SEXP maxDistanceSEXP, SEXP edgeTriadicSEXP, SEXP piiDeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edgeDistance(edgeDistanceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type valence(valenceSEXP);
    Rcpp::traits::input_parameter< double >::type piiBeta(piiBetaSEXP);
    Rcpp::traits::input_parameter< double >::type piiX(piiXSEXP);
    Rcpp::traits::input_parameter< int >::type maxDistance(maxDistanceSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type edgeTriadic(edgeTriadicSEXP);
    Rcpp::traits::input_parameter< double >::type piiDelta(piiDeltaSEXP);
    __result = Rcpp::wrap(piiTriadicCalc(edgeDistance, valence, piiBeta, piiX, maxDistance, edgeTriadic, piiDelta));
    return __result;
END_RCPP
}
